// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';


var BrowserAction = /* module */[];

var Tabs = /* module */[];

exports.BrowserAction = BrowserAction;
exports.Tabs = Tabs;
/* No side effect */
