// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var List = require("bs-platform/lib/js/list.js");
var Util = require("../shared/Util.bs.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

var colorList = /* :: */[
  "f11712",
  /* :: */[
    "ee2921",
    /* :: */[
      "ea352e",
      /* :: */[
        "e6403a",
        /* :: */[
          "e14948",
          /* :: */[
            "dc5154",
            /* :: */[
              "d9565c",
              /* :: */[
                "d25e6a",
                /* :: */[
                  "cc6476",
                  /* :: */[
                    "c76980",
                    /* :: */[
                      "c06e8a",
                      /* :: */[
                        "b87496",
                        /* :: */[
                          "b078a1",
                          /* :: */[
                            "a67dad",
                            /* :: */[
                              "9d82b7",
                              /* :: */[
                                "8c87c6",
                                /* :: */[
                                  "7e8bd1",
                                  /* :: */[
                                    "6291e1",
                                    /* :: */[
                                      "4d95ea",
                                      /* :: */[
                                        "0099f7",
                                        /* [] */0
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]
  ]
];

var colorListSize = List.length(colorList) - 1 | 0;

function getGradientIndex(param) {
  return (Caml_int32.imul(param[0], 365) + param[1] | 0) / 60 | 0;
}

function getColor(age) {
  return Css.style(Util.singletonList(Css.backgroundColor(Css.hex(List.nth(colorList, Math.min(colorListSize, getGradientIndex(age)))))));
}

var daysPerGradient = 60;

exports.colorList = colorList;
exports.colorListSize = colorListSize;
exports.daysPerGradient = daysPerGradient;
exports.getGradientIndex = getGradientIndex;
exports.getColor = getColor;
/* colorListSize Not a pure module */
