// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Util = require("./Util.bs.js");
var Axios = require("axios");

var inst = Axios.create({
      baseURL: process.env.API_URL
    });

function getStatus() {
  return Util.thenResolve((function (res) {
                return res.data;
              }), inst.get("/status"));
}

function getUsers(usernames) {
  return Util.thenResolve((function (res) {
                return res.data;
              }), inst.post("/users", /* record */[/* usernames */usernames]));
}

function deleteErrors() {
  return Util.thenResolve((function (res) {
                return res.data;
              }), inst.delete("/errors"));
}

exports.inst = inst;
exports.getStatus = getStatus;
exports.getUsers = getUsers;
exports.deleteErrors = deleteErrors;
/* inst Not a pure module */
