// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Util = require("./Util.bs.js");
var Types = require("./Types.bs.js");
var Axios = require("axios");

var inst = Axios.create({
      baseURL: "https://www.reddit.com"
    });

function getUser(username) {
  return Util.thenResolve(Types.Decode[/* user */0], Util.thenResolve((function (res) {
                    return res.data.data;
                  }), inst.get("/user/" + (String(username) + "/about.json"))));
}

exports.inst = inst;
exports.getUser = getUser;
/* inst Not a pure module */
