// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var Json_encode = require("@glennsl/bs-json/src/Json_encode.bs.js");

function user(json) {
  return /* record */[
          /* name */Json_decode.field("name", Json_decode.string, json),
          /* created_utc */Json_decode.withDefault(0.0, (function (param) {
                  return Json_decode.field("created_utc", Json_decode.$$float, param);
                }), json),
          /* link_karma */Json_decode.withDefault(0, (function (param) {
                  return Json_decode.field("link_karma", Json_decode.$$int, param);
                }), json),
          /* comment_karma */Json_decode.withDefault(0, (function (param) {
                  return Json_decode.field("comment_karma", Json_decode.$$int, param);
                }), json),
          /* id */Json_decode.withDefault("", (function (param) {
                  return Json_decode.field("id", Json_decode.string, param);
                }), json),
          /* is_suspended */Json_decode.withDefault(false, (function (param) {
                  return Json_decode.field("is_suspended", Json_decode.bool, param);
                }), json)
        ];
}

function count(json) {
  return /* record */[/* count */Json_decode.withDefault(0, (function (param) {
                  return Json_decode.field("count", Json_decode.$$int, param);
                }), json)];
}

var Decode = /* module */[
  /* user */user,
  /* count */count
];

function user$1(user$2) {
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "name",
                user$2[/* name */0]
              ],
              /* :: */[
                /* tuple */[
                  "created_utc",
                  user$2[/* created_utc */1]
                ],
                /* :: */[
                  /* tuple */[
                    "link_karma",
                    user$2[/* link_karma */2]
                  ],
                  /* :: */[
                    /* tuple */[
                      "comment_karma",
                      user$2[/* comment_karma */3]
                    ],
                    /* :: */[
                      /* tuple */[
                        "id",
                        user$2[/* id */4]
                      ],
                      /* :: */[
                        /* tuple */[
                          "is_suspended",
                          Json_encode.bool(user$2[/* is_suspended */5])
                        ],
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

var Encode = /* module */[/* user */user$1];

exports.Decode = Decode;
exports.Encode = Encode;
/* Json_encode Not a pure module */
